// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mgmt.proto

package mgmt

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MgmtBloomInfoResponse struct {
	HasBloom             bool     `protobuf:"varint,1,opt,name=has_bloom,json=hasBloom,proto3" json:"has_bloom,omitempty"`
	Capacity             uint64   `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Elements             uint64   `protobuf:"varint,3,opt,name=elements,proto3" json:"elements,omitempty"`
	Bits                 uint64   `protobuf:"varint,4,opt,name=bits,proto3" json:"bits,omitempty"`
	Hashfuncs            uint64   `protobuf:"varint,5,opt,name=hashfuncs,proto3" json:"hashfuncs,omitempty"`
	Fpprob               float64  `protobuf:"fixed64,6,opt,name=fpprob,proto3" json:"fpprob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MgmtBloomInfoResponse) Reset()         { *m = MgmtBloomInfoResponse{} }
func (m *MgmtBloomInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MgmtBloomInfoResponse) ProtoMessage()    {}
func (*MgmtBloomInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{0}
}

func (m *MgmtBloomInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MgmtBloomInfoResponse.Unmarshal(m, b)
}
func (m *MgmtBloomInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MgmtBloomInfoResponse.Marshal(b, m, deterministic)
}
func (m *MgmtBloomInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MgmtBloomInfoResponse.Merge(m, src)
}
func (m *MgmtBloomInfoResponse) XXX_Size() int {
	return xxx_messageInfo_MgmtBloomInfoResponse.Size(m)
}
func (m *MgmtBloomInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MgmtBloomInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MgmtBloomInfoResponse proto.InternalMessageInfo

func (m *MgmtBloomInfoResponse) GetHasBloom() bool {
	if m != nil {
		return m.HasBloom
	}
	return false
}

func (m *MgmtBloomInfoResponse) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *MgmtBloomInfoResponse) GetElements() uint64 {
	if m != nil {
		return m.Elements
	}
	return 0
}

func (m *MgmtBloomInfoResponse) GetBits() uint64 {
	if m != nil {
		return m.Bits
	}
	return 0
}

func (m *MgmtBloomInfoResponse) GetHashfuncs() uint64 {
	if m != nil {
		return m.Hashfuncs
	}
	return 0
}

func (m *MgmtBloomInfoResponse) GetFpprob() float64 {
	if m != nil {
		return m.Fpprob
	}
	return 0
}

type MgmtAliveRequest struct {
	Alive                string   `protobuf:"bytes,1,opt,name=alive,proto3" json:"alive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MgmtAliveRequest) Reset()         { *m = MgmtAliveRequest{} }
func (m *MgmtAliveRequest) String() string { return proto.CompactTextString(m) }
func (*MgmtAliveRequest) ProtoMessage()    {}
func (*MgmtAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{1}
}

func (m *MgmtAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MgmtAliveRequest.Unmarshal(m, b)
}
func (m *MgmtAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MgmtAliveRequest.Marshal(b, m, deterministic)
}
func (m *MgmtAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MgmtAliveRequest.Merge(m, src)
}
func (m *MgmtAliveRequest) XXX_Size() int {
	return xxx_messageInfo_MgmtAliveRequest.Size(m)
}
func (m *MgmtAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MgmtAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MgmtAliveRequest proto.InternalMessageInfo

func (m *MgmtAliveRequest) GetAlive() string {
	if m != nil {
		return m.Alive
	}
	return ""
}

type MgmtAliveResponse struct {
	Echo                 string   `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MgmtAliveResponse) Reset()         { *m = MgmtAliveResponse{} }
func (m *MgmtAliveResponse) String() string { return proto.CompactTextString(m) }
func (*MgmtAliveResponse) ProtoMessage()    {}
func (*MgmtAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{2}
}

func (m *MgmtAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MgmtAliveResponse.Unmarshal(m, b)
}
func (m *MgmtAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MgmtAliveResponse.Marshal(b, m, deterministic)
}
func (m *MgmtAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MgmtAliveResponse.Merge(m, src)
}
func (m *MgmtAliveResponse) XXX_Size() int {
	return xxx_messageInfo_MgmtAliveResponse.Size(m)
}
func (m *MgmtAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MgmtAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MgmtAliveResponse proto.InternalMessageInfo

func (m *MgmtAliveResponse) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

type MgmtBloomAddRequest struct {
	Ioc                  string   `protobuf:"bytes,1,opt,name=ioc,proto3" json:"ioc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MgmtBloomAddRequest) Reset()         { *m = MgmtBloomAddRequest{} }
func (m *MgmtBloomAddRequest) String() string { return proto.CompactTextString(m) }
func (*MgmtBloomAddRequest) ProtoMessage()    {}
func (*MgmtBloomAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{3}
}

func (m *MgmtBloomAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MgmtBloomAddRequest.Unmarshal(m, b)
}
func (m *MgmtBloomAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MgmtBloomAddRequest.Marshal(b, m, deterministic)
}
func (m *MgmtBloomAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MgmtBloomAddRequest.Merge(m, src)
}
func (m *MgmtBloomAddRequest) XXX_Size() int {
	return xxx_messageInfo_MgmtBloomAddRequest.Size(m)
}
func (m *MgmtBloomAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MgmtBloomAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MgmtBloomAddRequest proto.InternalMessageInfo

func (m *MgmtBloomAddRequest) GetIoc() string {
	if m != nil {
		return m.Ioc
	}
	return ""
}

type MgmtBloomAddResponse struct {
	Added                uint64   `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MgmtBloomAddResponse) Reset()         { *m = MgmtBloomAddResponse{} }
func (m *MgmtBloomAddResponse) String() string { return proto.CompactTextString(m) }
func (*MgmtBloomAddResponse) ProtoMessage()    {}
func (*MgmtBloomAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24cf82780fd24e73, []int{4}
}

func (m *MgmtBloomAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MgmtBloomAddResponse.Unmarshal(m, b)
}
func (m *MgmtBloomAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MgmtBloomAddResponse.Marshal(b, m, deterministic)
}
func (m *MgmtBloomAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MgmtBloomAddResponse.Merge(m, src)
}
func (m *MgmtBloomAddResponse) XXX_Size() int {
	return xxx_messageInfo_MgmtBloomAddResponse.Size(m)
}
func (m *MgmtBloomAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MgmtBloomAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MgmtBloomAddResponse proto.InternalMessageInfo

func (m *MgmtBloomAddResponse) GetAdded() uint64 {
	if m != nil {
		return m.Added
	}
	return 0
}

func init() {
	proto.RegisterType((*MgmtBloomInfoResponse)(nil), "mgmt.MgmtBloomInfoResponse")
	proto.RegisterType((*MgmtAliveRequest)(nil), "mgmt.MgmtAliveRequest")
	proto.RegisterType((*MgmtAliveResponse)(nil), "mgmt.MgmtAliveResponse")
	proto.RegisterType((*MgmtBloomAddRequest)(nil), "mgmt.MgmtBloomAddRequest")
	proto.RegisterType((*MgmtBloomAddResponse)(nil), "mgmt.MgmtBloomAddResponse")
}

func init() {
	proto.RegisterFile("mgmt.proto", fileDescriptor_24cf82780fd24e73)
}

var fileDescriptor_24cf82780fd24e73 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x3d, 0x8f, 0xda, 0x40,
	0x10, 0x95, 0xc1, 0x20, 0x33, 0x34, 0x64, 0x43, 0x88, 0x63, 0x28, 0x90, 0x1b, 0x5c, 0x44, 0xb6,
	0x94, 0x34, 0x91, 0xa2, 0x48, 0x01, 0x92, 0x22, 0x45, 0x14, 0x69, 0xe9, 0xd2, 0x44, 0xfe, 0x18,
	0x7f, 0x48, 0xb6, 0xd7, 0xf1, 0xae, 0x91, 0xf8, 0x63, 0xf9, 0x11, 0xf9, 0x55, 0xa7, 0x5d, 0xdb,
	0x70, 0x07, 0x5c, 0x71, 0xdd, 0xbc, 0x79, 0x6f, 0x66, 0xdf, 0xec, 0x03, 0x28, 0x92, 0x42, 0xb8,
	0x55, 0xcd, 0x04, 0x23, 0xba, 0xac, 0xad, 0x65, 0xc2, 0x58, 0x92, 0xa3, 0xa7, 0x7a, 0x41, 0x13,
	0x7b, 0x58, 0x54, 0xe2, 0xd4, 0x4a, 0xec, 0x7f, 0x1a, 0xbc, 0xf9, 0x99, 0x14, 0x62, 0x97, 0x33,
	0x56, 0xfc, 0x28, 0x63, 0x46, 0x91, 0x57, 0xac, 0xe4, 0x48, 0x96, 0x30, 0x49, 0x7d, 0xfe, 0x27,
	0x90, 0x84, 0xa9, 0xad, 0x35, 0xc7, 0xa0, 0x46, 0xea, 0x73, 0x25, 0x24, 0x16, 0x18, 0xa1, 0x5f,
	0xf9, 0x61, 0x26, 0x4e, 0xe6, 0x60, 0xad, 0x39, 0x3a, 0x3d, 0x63, 0xc9, 0x61, 0x8e, 0x05, 0x96,
	0x82, 0x9b, 0xc3, 0x96, 0xeb, 0x31, 0x21, 0xa0, 0x07, 0x99, 0xe0, 0xa6, 0xae, 0xfa, 0xaa, 0x26,
	0x2b, 0xf5, 0x50, 0x1a, 0x37, 0x65, 0xc8, 0xcd, 0x91, 0x22, 0x2e, 0x0d, 0xb2, 0x80, 0x71, 0x5c,
	0x55, 0x35, 0x0b, 0xcc, 0xf1, 0x5a, 0x73, 0x34, 0xda, 0x21, 0xdb, 0x81, 0x99, 0xf4, 0xbd, 0xcd,
	0xb3, 0x23, 0x52, 0xfc, 0xdb, 0x20, 0x17, 0x64, 0x0e, 0x23, 0x5f, 0x62, 0x65, 0x77, 0x42, 0x5b,
	0x60, 0x6f, 0xe0, 0xd5, 0x23, 0x65, 0x77, 0x1d, 0x01, 0x1d, 0xc3, 0x94, 0x75, 0x4a, 0x55, 0xdb,
	0x1b, 0x78, 0x7d, 0xfe, 0x8a, 0x6d, 0x14, 0xf5, 0x5b, 0x67, 0x30, 0xcc, 0x58, 0xd8, 0x29, 0x65,
	0x69, 0xbf, 0x87, 0xf9, 0x53, 0x61, 0xb7, 0x54, 0xbe, 0x1f, 0x45, 0x18, 0x29, 0xad, 0x4e, 0x5b,
	0xf0, 0xe1, 0xff, 0x00, 0xa6, 0x52, 0x7e, 0xc0, 0xfa, 0x98, 0x85, 0x48, 0x3e, 0xc1, 0x48, 0x79,
	0x21, 0x0b, 0x57, 0x65, 0x75, 0x7d, 0x86, 0xf5, 0xf6, 0xa6, 0xdf, 0xed, 0xff, 0x0a, 0x93, 0x73,
	0x4e, 0x64, 0xe1, 0xb6, 0xb9, 0xba, 0x7d, 0xae, 0xee, 0x77, 0x99, 0xab, 0xb5, 0xbc, 0x4c, 0xdf,
	0x86, 0xba, 0x07, 0xa3, 0x77, 0x4d, 0xde, 0x5d, 0x09, 0x2f, 0x27, 0x5b, 0xd6, 0x3d, 0xaa, 0x5d,
	0xe1, 0x68, 0xe4, 0x73, 0x67, 0xe3, 0xe0, 0xab, 0x23, 0xee, 0xdb, 0x78, 0xa6, 0x4f, 0xbe, 0xc0,
	0x54, 0x0d, 0x53, 0xcc, 0x99, 0x1f, 0xbd, 0x74, 0x7c, 0xb7, 0xfa, 0x6d, 0x25, 0x99, 0x48, 0x9b,
	0xc0, 0x0d, 0x59, 0xe1, 0x7d, 0xdb, 0x1f, 0x7e, 0x79, 0x31, 0x1e, 0xb1, 0xf6, 0xa4, 0xe1, 0x60,
	0xac, 0xd4, 0x1f, 0x1f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xbf, 0x67, 0x4d, 0x05, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MgmtServiceClient is the client API for MgmtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MgmtServiceClient interface {
	Alive(ctx context.Context, in *MgmtAliveRequest, opts ...grpc.CallOption) (*MgmtAliveResponse, error)
	BloomInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MgmtBloomInfoResponse, error)
	BloomAdd(ctx context.Context, opts ...grpc.CallOption) (MgmtService_BloomAddClient, error)
	BloomSave(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	BloomReload(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type mgmtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMgmtServiceClient(cc grpc.ClientConnInterface) MgmtServiceClient {
	return &mgmtServiceClient{cc}
}

func (c *mgmtServiceClient) Alive(ctx context.Context, in *MgmtAliveRequest, opts ...grpc.CallOption) (*MgmtAliveResponse, error) {
	out := new(MgmtAliveResponse)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtService/Alive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtServiceClient) BloomInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MgmtBloomInfoResponse, error) {
	out := new(MgmtBloomInfoResponse)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtService/BloomInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtServiceClient) BloomAdd(ctx context.Context, opts ...grpc.CallOption) (MgmtService_BloomAddClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MgmtService_serviceDesc.Streams[0], "/mgmt.MgmtService/BloomAdd", opts...)
	if err != nil {
		return nil, err
	}
	x := &mgmtServiceBloomAddClient{stream}
	return x, nil
}

type MgmtService_BloomAddClient interface {
	Send(*MgmtBloomAddRequest) error
	CloseAndRecv() (*MgmtBloomAddResponse, error)
	grpc.ClientStream
}

type mgmtServiceBloomAddClient struct {
	grpc.ClientStream
}

func (x *mgmtServiceBloomAddClient) Send(m *MgmtBloomAddRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mgmtServiceBloomAddClient) CloseAndRecv() (*MgmtBloomAddResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MgmtBloomAddResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mgmtServiceClient) BloomSave(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtService/BloomSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mgmtServiceClient) BloomReload(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/mgmt.MgmtService/BloomReload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MgmtServiceServer is the server API for MgmtService service.
type MgmtServiceServer interface {
	Alive(context.Context, *MgmtAliveRequest) (*MgmtAliveResponse, error)
	BloomInfo(context.Context, *empty.Empty) (*MgmtBloomInfoResponse, error)
	BloomAdd(MgmtService_BloomAddServer) error
	BloomSave(context.Context, *empty.Empty) (*empty.Empty, error)
	BloomReload(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedMgmtServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMgmtServiceServer struct {
}

func (*UnimplementedMgmtServiceServer) Alive(ctx context.Context, req *MgmtAliveRequest) (*MgmtAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alive not implemented")
}
func (*UnimplementedMgmtServiceServer) BloomInfo(ctx context.Context, req *empty.Empty) (*MgmtBloomInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BloomInfo not implemented")
}
func (*UnimplementedMgmtServiceServer) BloomAdd(srv MgmtService_BloomAddServer) error {
	return status.Errorf(codes.Unimplemented, "method BloomAdd not implemented")
}
func (*UnimplementedMgmtServiceServer) BloomSave(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BloomSave not implemented")
}
func (*UnimplementedMgmtServiceServer) BloomReload(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BloomReload not implemented")
}

func RegisterMgmtServiceServer(s *grpc.Server, srv MgmtServiceServer) {
	s.RegisterService(&_MgmtService_serviceDesc, srv)
}

func _MgmtService_Alive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MgmtAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtServiceServer).Alive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtService/Alive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtServiceServer).Alive(ctx, req.(*MgmtAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtService_BloomInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtServiceServer).BloomInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtService/BloomInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtServiceServer).BloomInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtService_BloomAdd_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MgmtServiceServer).BloomAdd(&mgmtServiceBloomAddServer{stream})
}

type MgmtService_BloomAddServer interface {
	SendAndClose(*MgmtBloomAddResponse) error
	Recv() (*MgmtBloomAddRequest, error)
	grpc.ServerStream
}

type mgmtServiceBloomAddServer struct {
	grpc.ServerStream
}

func (x *mgmtServiceBloomAddServer) SendAndClose(m *MgmtBloomAddResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mgmtServiceBloomAddServer) Recv() (*MgmtBloomAddRequest, error) {
	m := new(MgmtBloomAddRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MgmtService_BloomSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtServiceServer).BloomSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtService/BloomSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtServiceServer).BloomSave(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MgmtService_BloomReload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MgmtServiceServer).BloomReload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mgmt.MgmtService/BloomReload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MgmtServiceServer).BloomReload(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MgmtService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mgmt.MgmtService",
	HandlerType: (*MgmtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Alive",
			Handler:    _MgmtService_Alive_Handler,
		},
		{
			MethodName: "BloomInfo",
			Handler:    _MgmtService_BloomInfo_Handler,
		},
		{
			MethodName: "BloomSave",
			Handler:    _MgmtService_BloomSave_Handler,
		},
		{
			MethodName: "BloomReload",
			Handler:    _MgmtService_BloomReload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BloomAdd",
			Handler:       _MgmtService_BloomAdd_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mgmt.proto",
}
