// Copyright (c) 2020, DCSO GmbH

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.2
// source: api/hateoas.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// HateoasLink defines a HATEOAS link.
type HateoasLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Href maps link element can be mapped to an HTTP link.
	Href string `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	// Rel conveys the relation type.
	Rel string `protobuf:"bytes,2,opt,name=rel,proto3" json:"rel,omitempty"`
	// Type defines the HTTP method for the link element.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Length is an optional element recommended for "enclosure" relations.
	Length int64 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *HateoasLink) Reset() {
	*x = HateoasLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hateoas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HateoasLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HateoasLink) ProtoMessage() {}

func (x *HateoasLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_hateoas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HateoasLink.ProtoReflect.Descriptor instead.
func (*HateoasLink) Descriptor() ([]byte, []int) {
	return file_api_hateoas_proto_rawDescGZIP(), []int{0}
}

func (x *HateoasLink) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *HateoasLink) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

func (x *HateoasLink) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HateoasLink) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Hateoas wraps a slice of (optional) HateoasLinks.
type Hateoas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// XLinks to avoid mingling with the automatic name assignment while
	// maintaining REST API stability towards DCSO's portal.
	XLinks []*HateoasLink `protobuf:"bytes,1,rep,name=_links,json=Links,proto3" json:"_links,omitempty"`
}

func (x *Hateoas) Reset() {
	*x = Hateoas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hateoas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hateoas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hateoas) ProtoMessage() {}

func (x *Hateoas) ProtoReflect() protoreflect.Message {
	mi := &file_api_hateoas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hateoas.ProtoReflect.Descriptor instead.
func (*Hateoas) Descriptor() ([]byte, []int) {
	return file_api_hateoas_proto_rawDescGZIP(), []int{1}
}

func (x *Hateoas) GetXLinks() []*HateoasLink {
	if x != nil {
		return x.XLinks
	}
	return nil
}

var File_api_hateoas_proto protoreflect.FileDescriptor

var file_api_hateoas_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x61, 0x74, 0x65, 0x6f, 0x61, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x5f, 0x0a, 0x0b, 0x48, 0x61, 0x74, 0x65,
	0x6f, 0x61, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x72, 0x65, 0x66, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x72, 0x65, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x32, 0x0a, 0x07, 0x48, 0x61, 0x74,
	0x65, 0x6f, 0x61, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x61, 0x74, 0x65, 0x6f,
	0x61, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x24, 0x5a,
	0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x43, 0x53, 0x4f,
	0x2f, 0x66, 0x65, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x74, 0x65, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_hateoas_proto_rawDescOnce sync.Once
	file_api_hateoas_proto_rawDescData = file_api_hateoas_proto_rawDesc
)

func file_api_hateoas_proto_rawDescGZIP() []byte {
	file_api_hateoas_proto_rawDescOnce.Do(func() {
		file_api_hateoas_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_hateoas_proto_rawDescData)
	})
	return file_api_hateoas_proto_rawDescData
}

var file_api_hateoas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_hateoas_proto_goTypes = []interface{}{
	(*HateoasLink)(nil), // 0: api.HateoasLink
	(*Hateoas)(nil),     // 1: api.Hateoas
}
var file_api_hateoas_proto_depIdxs = []int32{
	0, // 0: api.Hateoas._links:type_name -> api.HateoasLink
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_hateoas_proto_init() }
func file_api_hateoas_proto_init() {
	if File_api_hateoas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_hateoas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HateoasLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hateoas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hateoas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_hateoas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_hateoas_proto_goTypes,
		DependencyIndexes: file_api_hateoas_proto_depIdxs,
		MessageInfos:      file_api_hateoas_proto_msgTypes,
	}.Build()
	File_api_hateoas_proto = out.File
	file_api_hateoas_proto_rawDesc = nil
	file_api_hateoas_proto_goTypes = nil
	file_api_hateoas_proto_depIdxs = nil
}
