// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/hateoas.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HateoasLink defines a HATEOAS link.
type HateoasLink struct {
	// Href maps link element can be mapped to an HTTP link.
	Href string `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	// Rel conveys the relation type.
	Rel string `protobuf:"bytes,2,opt,name=rel,proto3" json:"rel,omitempty"`
	// Type defines the HTTP method for the link element.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Length is an optional element recommended for "enclosure" relations.
	Length               int64    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HateoasLink) Reset()         { *m = HateoasLink{} }
func (m *HateoasLink) String() string { return proto.CompactTextString(m) }
func (*HateoasLink) ProtoMessage()    {}
func (*HateoasLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ae5b8d6f8929caf, []int{0}
}

func (m *HateoasLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HateoasLink.Unmarshal(m, b)
}
func (m *HateoasLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HateoasLink.Marshal(b, m, deterministic)
}
func (m *HateoasLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HateoasLink.Merge(m, src)
}
func (m *HateoasLink) XXX_Size() int {
	return xxx_messageInfo_HateoasLink.Size(m)
}
func (m *HateoasLink) XXX_DiscardUnknown() {
	xxx_messageInfo_HateoasLink.DiscardUnknown(m)
}

var xxx_messageInfo_HateoasLink proto.InternalMessageInfo

func (m *HateoasLink) GetHref() string {
	if m != nil {
		return m.Href
	}
	return ""
}

func (m *HateoasLink) GetRel() string {
	if m != nil {
		return m.Rel
	}
	return ""
}

func (m *HateoasLink) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HateoasLink) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

// Hateoas wraps a slice of (optional) HateoasLinks.
type Hateoas struct {
	// XLinks to avoid mingling with the automatic name assignment while
	// maintaining REST API stability towards DCSO's portal.
	XLinks               []*HateoasLink `protobuf:"bytes,1,rep,name=_links,json=Links,proto3" json:"_links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Hateoas) Reset()         { *m = Hateoas{} }
func (m *Hateoas) String() string { return proto.CompactTextString(m) }
func (*Hateoas) ProtoMessage()    {}
func (*Hateoas) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ae5b8d6f8929caf, []int{1}
}

func (m *Hateoas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hateoas.Unmarshal(m, b)
}
func (m *Hateoas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hateoas.Marshal(b, m, deterministic)
}
func (m *Hateoas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hateoas.Merge(m, src)
}
func (m *Hateoas) XXX_Size() int {
	return xxx_messageInfo_Hateoas.Size(m)
}
func (m *Hateoas) XXX_DiscardUnknown() {
	xxx_messageInfo_Hateoas.DiscardUnknown(m)
}

var xxx_messageInfo_Hateoas proto.InternalMessageInfo

func (m *Hateoas) GetXLinks() []*HateoasLink {
	if m != nil {
		return m.XLinks
	}
	return nil
}

func init() {
	proto.RegisterType((*HateoasLink)(nil), "api.HateoasLink")
	proto.RegisterType((*Hateoas)(nil), "api.Hateoas")
}

func init() { proto.RegisterFile("api/hateoas.proto", fileDescriptor_3ae5b8d6f8929caf) }

var fileDescriptor_3ae5b8d6f8929caf = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4b, 0xc0, 0x30,
	0x10, 0x85, 0x89, 0xa9, 0x15, 0xd3, 0xa5, 0x66, 0x90, 0x8c, 0xa5, 0x08, 0x76, 0x4a, 0xa0, 0xfe,
	0x03, 0x75, 0x70, 0x10, 0x84, 0xba, 0xb9, 0x94, 0x54, 0xae, 0xcd, 0xd1, 0x9a, 0x84, 0x24, 0x0a,
	0xfe, 0x7b, 0x49, 0xdb, 0xc1, 0xe5, 0xf8, 0xee, 0xf1, 0xe0, 0xe3, 0xb1, 0x1b, 0xed, 0x51, 0x19,
	0x9d, 0xc0, 0xe9, 0x28, 0x7d, 0x70, 0xc9, 0x71, 0xaa, 0x3d, 0xb6, 0x23, 0xab, 0x5e, 0x8e, 0xf4,
	0x15, 0xed, 0xca, 0x39, 0x2b, 0x4c, 0x80, 0x59, 0x90, 0x86, 0x74, 0xd7, 0xc3, 0xce, 0xbc, 0x66,
	0x34, 0xc0, 0x26, 0x2e, 0xf6, 0x28, 0x63, 0x6e, 0xa5, 0x5f, 0x0f, 0x82, 0x1e, 0xad, 0xcc, 0xfc,
	0x96, 0x95, 0x1b, 0xd8, 0x25, 0x19, 0x51, 0x34, 0xa4, 0xa3, 0xc3, 0xf9, 0xb5, 0x3d, 0xbb, 0x3a,
	0x05, 0xfc, 0x9e, 0x95, 0xe3, 0x86, 0x76, 0x8d, 0x82, 0x34, 0xb4, 0xab, 0xfa, 0x5a, 0x6a, 0x8f,
	0xf2, 0x9f, 0x7e, 0xb8, 0xcc, 0x37, 0x3e, 0xde, 0x7d, 0xb4, 0x0b, 0x26, 0xf3, 0x3d, 0xc9, 0x4f,
	0xf7, 0xa5, 0x9e, 0x9f, 0xde, 0xdf, 0xd4, 0x0c, 0x3f, 0x10, 0x54, 0x4c, 0x60, 0x5d, 0xc4, 0xa8,
	0xb4, 0xc7, 0xa9, 0xdc, 0x67, 0x3c, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0x50, 0x95, 0xf2, 0x9e,
	0xdb, 0x00, 0x00, 0x00,
}
