---
name: Go build

on:
  - push
  - pull_request

jobs:
  build:
    name: "Go build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Install non-Go deps
      run: |
             sudo apt update
             sudo apt -yq install redis-server

    - name: Get and build deps
      run: go get -v -t ./...

    - name: Build executable
      run: go build -v -o fever cmd/fever/main.go

    - name: Run tests
      run: go test -v ./...
